name: End-to-end tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_APP_ID: ${{ secrets.BROWSERSTACK_APP_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies and Run Tests
        run: |
          npm install
          npm run test

      - name: Generate Report
        run: npm run report:generate

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
